apiVersion: apps/v1
kind: Deployment
metadata:
  name: jack-dep
  labels:
    app: jack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jack
  template: 
    metadata:
      labels:
        app: jack
    spec:
      containers:
       - name: ubuntu
         image: ubuntu:latest
         # Just sleep forever
         command: [ "sleep" ]
         args: [ "infinity" ]
