apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa
  namespace: tnf
spec:
  minReplicas: 3
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 2
    type: Resource
  scaleTargetRef:
    apiVersion: tutorial.my.domain/v1
    kind: Foo
    name: foo-01
